[metadata]
version = "1.0"

[versions]
errorprone = "2.19.1"
errorproneGradle = "3.1.0"
junit = "5.9.3"
indra = "3.1.3"
spongeConvention = "2.2.0"
spotless = "6.21.0"

[libraries]
errorprone = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

[plugins]
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorproneGradle" }
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-crossdoc = { id = "net.kyori.indra.crossdoc", version.ref = "indra" }
indra-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }
spongeConvention = { id = "org.spongepowered.gradle.sponge.dev", version.ref = "spongeConvention" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
